// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN3wT9D75pUhVDTvG6E2Ro3A4D2XCQOkU',
    appId: '1:488278102256:web:9f6402a21477c0484b3235',
    messagingSenderId: '488278102256',
    projectId: 'autonomous-robot-2b4c4',
    authDomain: 'autonomous-robot-2b4c4.firebaseapp.com',
    storageBucket: 'autonomous-robot-2b4c4.firebasestorage.app',
    measurementId: 'G-58BVY5PMES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ0nZh_sKD4GN0lc3w2MZGSV1kIPVlbBg',
    appId: '1:488278102256:android:28967bf86ec73dce4b3235',
    messagingSenderId: '488278102256',
    projectId: 'autonomous-robot-2b4c4',
    storageBucket: 'autonomous-robot-2b4c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFAzEODfFinOmj2vtbcKUBezILmbimjug',
    appId: '1:488278102256:ios:eb44658c8b9cd3f94b3235',
    messagingSenderId: '488278102256',
    projectId: 'autonomous-robot-2b4c4',
    storageBucket: 'autonomous-robot-2b4c4.firebasestorage.app',
    iosBundleId: 'com.example.pathPlanning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFAzEODfFinOmj2vtbcKUBezILmbimjug',
    appId: '1:488278102256:ios:eb44658c8b9cd3f94b3235',
    messagingSenderId: '488278102256',
    projectId: 'autonomous-robot-2b4c4',
    storageBucket: 'autonomous-robot-2b4c4.firebasestorage.app',
    iosBundleId: 'com.example.pathPlanning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN3wT9D75pUhVDTvG6E2Ro3A4D2XCQOkU',
    appId: '1:488278102256:web:1c1c70e7e6a1bdd64b3235',
    messagingSenderId: '488278102256',
    projectId: 'autonomous-robot-2b4c4',
    authDomain: 'autonomous-robot-2b4c4.firebaseapp.com',
    storageBucket: 'autonomous-robot-2b4c4.firebasestorage.app',
    measurementId: 'G-YD74SMM6E5',
  );
}
