"""Add orders and robot_state

Revision ID: 637af8dd3c4c
Revises: bf32eb84be19
Create Date: 2026-07-14 09:22:09.422252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637af8dd3c4c'
down_revision = 'bf32eb84be19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('pickup_room', sa.String(length=100), nullable=True),
    sa.Column('dropoff_room', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robot_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('current_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robot_state')
    op.drop_table('orders')
    # ### end Alembic commands ###
