"""Add label and region dimensions to Room model

Revision ID: 7d051ae0d7f0
Revises: a2bf428c86f0
Create Date: 2026-07-11 20:50:24.084168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d051ae0d7f0'
down_revision = 'a2bf428c86f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('label_y', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('region_width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('region_height', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('region_height')
        batch_op.drop_column('region_width')
        batch_op.drop_column('label_y')
        batch_op.drop_column('label_x')

    # ### end Alembic commands ###
