"""Add sender_name, scheduled_at, and is_dispatched to Delivery model

Revision ID: bf32eb84be19
Revises: 33074baf27c6
Create Date: 2026-07-11 21:26:52.072672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf32eb84be19'
down_revision = '33074baf27c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_name', sa.String(length=100), nullable=False, server_default='Unknown Sender'))
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_dispatched', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('is_dispatched')
        batch_op.drop_column('scheduled_at')
        batch_op.drop_column('sender_name')

    # ### end Alembic commands ###
